version: '3.8'

services:
  web:
    build: ./Diploma
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Diploma/:/usr/src/Diploma/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev