# Generated by Django 4.1.3 on 2023-05-14 20:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatehtml',
            name='template_html',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='templates_html', verbose_name='Html шаблон'),
        ),
    ]
