# Generated by Django 4.1.3 on 2023-04-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_film_budget_alter_film_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
