# Generated by Django 4.1.3 on 2023-04-14 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_film_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Адрес должен начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=150, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Имя должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Фамилия должна начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(13), django.core.validators.ProhibitNullCharactersValidator(), django.core.validators.RegexValidator('^\\+38 \\(\\d{3}\\) \\d{3}-?\\d{2}-?\\d{2}$', message='Неверно введён номер телефона.Пример ввода: +38 (098) 567-81-23')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='backimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bottomcarousel',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bottomcarousel',
            name='link',
            field=models.URLField(default='', validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator('\\w*:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,4}\x08([-a-zA-Z0-9@:%_\\+.~#?&\\/=]*)', message='Неверный url')], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cafebarmenu',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150, 'Длина названия блюда должна быть не более 150ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название блюда должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия кинотеатра должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название кинотеатра должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cinemaimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='film',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='card_img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Картинка карточки'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='film',
            name='legal_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(8)], verbose_name='Мин Возраст'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_link',
            field=models.URLField(max_length=100, validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator('\\w*:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,4}\x08([-a-zA-Z0-9@:%_\\+.~#?&\\/=]*)', message='Неверный url адресс')], verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='filmimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='hall',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='scheme',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Cхема зала'),
        ),
        migrations.AlterField(
            model_name='hallimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(13), django.core.validators.ProhibitNullCharactersValidator(), django.core.validators.RegexValidator('^\\(\\d{3}\\) \\d{3}-?\\d{2}-?\\d{2}$', message='Неверно введён номер телефона.Пример ввода: (098) 567-81-23')]),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='number2',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(13), django.core.validators.ProhibitNullCharactersValidator(), django.core.validators.RegexValidator('^\\(\\d{3}\\) \\d{3}-?\\d{2}-?\\d{2}$', message='Неверно введён номер телефона.Пример ввода: (098) 567-81-23')]),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='seo_text',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='news',
            name='card_img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Картинка карточки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Длина названия новости должна быть не более 30ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название новости должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator('\\w*:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,4}\x08([-a-zA-Z0-9@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='page',
            name='first_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Первая картинка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия страницы должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название страницы должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='second_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Вторая картинка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='third_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Третья картинка'),
        ),
        migrations.AlterField(
            model_name='pageimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='keywords',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='seo_description',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Название не более 20ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator('\\w*:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,4}\x08([-a-zA-Z0-9@:%_\\+.~#?&\\/=]*)', message='Неверный url')], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='card_img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Картинка карточки'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Длина названия акции должна быть не более 30ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название акции должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='video_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator('\\w*:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,4}\x08([-a-zA-Z0-9@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='stockimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='templatehtml',
            name='template_html',
            field=models.FileField(upload_to='templates_html', validators=[django.core.validators.FileExtensionValidator(['html'])], verbose_name='Html шаблон'),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='link',
            field=models.URLField(default='', validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator('\\w*:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,4}\x08([-a-zA-Z0-9@:%_\\+.~#?&\\/=]*)', message='Неверный url')], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='title',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Заголовок должен начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name=''),
        ),
    ]
