# Generated by Django 4.1.3 on 2023-04-14 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_account_phone_alter_mainpage_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(default='', validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description2',
            field=models.TextField(default='', validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Второе описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='short_description',
            field=models.TextField(default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
    ]
