# Generated by Django 4.1.3 on 2023-04-14 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_cinema_description_alter_hall_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafebarmenu',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название блюда должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='cafebarmenu',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cafebarmenu',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес(грамм)'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название кинотеатра должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер зала'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description2',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Второе описание'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
    ]
