# Generated by Django 4.1.3 on 2023-04-16 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_cafebarmenu_name_alter_cafebarmenu_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer_link',
            field=models.URLField(max_length=100, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='link',
            field=models.URLField(default='', verbose_name=''),
        ),
    ]
