# Generated by Django 4.1.3 on 2023-04-29 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_film_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomcarousel',
            name='link',
            field=models.URLField(default='', validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinemaimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='coordinate',
            field=models.TextField(verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='number',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.MaxLengthValidator(19), django.core.validators.MinLengthValidator(19), django.core.validators.ProhibitNullCharactersValidator(), django.core.validators.RegexValidator('^\\+38 \\(\\d{3}\\) \\d{3}-?\\d{2}-?\\d{2}$', message='Неверно введён номер телефона.Пример ввода: +38 (098) 567-81-23')], verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='number2',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.MaxLengthValidator(19), django.core.validators.MinLengthValidator(19), django.core.validators.ProhibitNullCharactersValidator(), django.core.validators.RegexValidator('^\\+38 \\(\\d{3}\\) \\d{3}-?\\d{2}-?\\d{2}$', message='Неверно введён номер телефона.Пример ввода: +38 (098) 567-81-23')], verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='seo_text',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='SEO текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description2',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Второе описание'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='short_description',
            field=models.TextField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='video_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='link',
            field=models.URLField(default='', validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name=''),
        ),
    ]
