# Generated by Django 4.1.3 on 2023-04-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_bottomcarousel_link_alter_cinema_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='film',
            name='card_img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка карточки'),
        ),
    ]
