# Generated by Django 4.1.3 on 2023-04-30 04:52

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_page_options_alter_film_card_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bottomcarousel',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='cinemaimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='coordinate',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='film',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='filmimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='hall',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='scheme',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Cхема зала'),
        ),
        migrations.AlterField(
            model_name='hallimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='news',
            name='card_img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка карточки'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='page',
            name='first_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Первая картинка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='second_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Вторая картинка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='third_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Третья картинка'),
        ),
        migrations.AlterField(
            model_name='pageimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='banner',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='card_img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка карточки'),
        ),
        migrations.AlterField(
            model_name='stockimg',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='templatehtml',
            name='template_html',
            field=models.FileField(upload_to='templates_html', verbose_name='Html шаблон'),
        ),
        migrations.AlterField(
            model_name='topcarousel',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name=''),
        ),
    ]
