# Generated by Django 4.1.3 on 2023-05-03 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_contact_geolocation_alter_contact_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoblock',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='seo_description_en',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='seo_description_ru',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_en',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, 'Название не более 20ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, 'Название не более 20ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='url_en',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='url_ru',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка'),
        ),
    ]
