# Generated by Django 4.1.3 on 2023-05-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_contact_geolocation_alter_contact_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockimg',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockImg',
        ),
    ]
