# Generated by Django 4.1.3 on 2023-05-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_seoblock_keywords_en_seoblock_keywords_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoblock',
            name='keywords_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='keywords_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='url_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='url_ru',
        ),
    ]
