# Generated by Django 4.1.3 on 2023-05-06 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('turn_on', models.BooleanField(default=False, verbose_name='ВКЛ/ВЫКЛ')),
                ('video_link', models.URLField(validators=[django.core.validators.URLValidator(message='XYZ', regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)')], verbose_name='Ссылка на видео')),
                ('banner', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('card_img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка карточки')),
                ('seo_block', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='StockImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.stock')),
            ],
            options={
                'db_table': 'stock_imgs',
            },
        ),
    ]
