# Generated by Django 4.1.3 on 2023-05-06 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_stock_description_stock_name_stock_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description_en',
            field=models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stock',
            name='description_ru',
            field=models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stock',
            name='name_en',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MaxLengthValidator(30, 'Длина названия акции должна быть не более 30ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название акции должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stock',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MaxLengthValidator(30, 'Длина названия акции должна быть не более 30ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название акции должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stock',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='stock',
            name='short_description_ru',
            field=models.TextField(blank=True, max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
    ]
