# Generated by Django 4.1.3 on 2023-05-06 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_stock_description_en_stock_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafebarmenu',
            name='name_en',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название блюда должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AddField(
            model_name='cafebarmenu',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название блюда должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_en',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название кинотеатра должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название кинотеатра должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editor',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editor',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ru',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='film',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_en',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='seo_text_en',
            field=models.TextField(max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='SEO текст'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='seo_text_ru',
            field=models.TextField(max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='SEO текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_en',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MaxLengthValidator(30, 'Длина названия новости должна быть не более 30ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название новости должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MaxLengthValidator(30, 'Длина названия новости должна быть не более 30ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название новости должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='operator',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_ru',
            field=models.TextField(max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы.'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия страницы должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название страницы должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Длина названия страницы должна быть не более 100 символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название страницы должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scriptwriter',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scriptwriter',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='seo_description_en',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='seo_description_ru',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Описание должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_en',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, 'Название не более 20ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, 'Название не более 20ти символов.'), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', 'Название должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='technologytype',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technologytype',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topcarousel',
            name='title_en',
            field=models.CharField(default='', max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Заголовок должен начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name=''),
        ),
        migrations.AddField(
            model_name='topcarousel',
            name='title_ru',
            field=models.CharField(default='', max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Заголовок должен начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name=''),
        ),
    ]
