# Generated by Django 4.1.3 on 2023-05-07 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_remove_cafebarmenu_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafebarmenu',
            name='name_en',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название блюда должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cafebarmenu',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[A-ZА-Я]{1}.*', message='Название блюда должно начинаться с заглавной буквы'), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название'),
        ),
    ]
